### ISSUE TITLE
Images are rendered out in huge file sizes

### ISSUE THREAD

**Issue by code-mattclaffey** [dcgauld/gulp-responsive-images#3]
Hey, 

I used this task yesterday and I was wondering if there are any options to render out quality for these images?

Example: 

hero-1.jpg - 268kb

Task config:

"hero/*.jpg" : [
      {
        width: 3340,
        height: 1100,
        suffix: "-large-2x"
      },
      {
        width: 1680,
        height: 550,
        suffix: "-large-1x"
      },
      {
        width: 2040,
        height: 800,
        suffix: "-medium-2x",
        crop: true
      },
      {
        width: 1020,
        height: 400,
        suffix: "-medium-1x",
        crop: true
      },
      {
        width: 1360,
        height: 1000,
        suffix: "-small-2x",
        crop: true
      },
      {
        width: 680,
        height: 500,
        suffix: "-small-1x",
        crop: true
      },
    {
      width: 960,
      height: 1280,
      suffix: "-vsmall-2x",
      crop: true
    },
    {
      width: 480,
      height: 640,
      suffix: "-vsmall-1x",
      crop: true
    }
  ]

Images are rendered out correctly but the file sizes are:

Hero-1-large-2x.jpg - 1.3mb
Hero-1-large-1x.jpg - 495kb
Hero-1-medium-2x.jpg - 787kb
Hero-1-medium-1x.jpg - 282kb

And so on. 

Is there an option for this or do I need to pipe an image minify task with it?

**Comment by code-mattclaffey** [comment]
I fixed the issue. It does have an option of 'quality' but it would be better if it was in the documentation.

**Comment by dcgauld** [comment]
Glad you sorted out the issue. Agree that the documentation is severely lacking. When I get some time I'll try to write some better docs.

**Comment by code-mattclaffey** [comment]
If need be I can add it to the readme if you dont have the time?

**Comment by code-mattclaffey** [comment]
I tried to update the readme to this but I didnt have access. 

# gulp-responsive-images

A simple Gulp plugin that allows the resizing and renaming of images, primarily for responsive applications. It uses GraphicsMagick to allow simple resizing, cropping, quality control and more.

## Install

Install with [npm](https://npmjs.org/package/gulp-responsive-images).

```
npm install --save-dev gulp-responsive-images
```

### GraphicsMagick

gulp-responsive-images requires GraphicsMagick to function. Installation is simple:

Ubuntu:

``` shell
apt-get install graphicsmagick
```

Mac OS X (using [Homebrew](http://brew.sh/)):

``` shell
brew install graphicsmagick
```

## Common Options

``` js
// Image.js

var images = {
  'hero.png': [
      {
      crop: false,
      format: null,
      gravity: 'Center',
      height: 100,
      overwrite: true,
      quality: 100,
      rename: null,
      percentage: false,
      sharpen: false,
      suffix: '-100'
      upscale: false,
      width: 100
    }
  ]
};

module.exports = images;      

});

```

## Example

``` js
var gulp = require('gulp');
var responsive = require('gulp-responsive-images');
var images = require('/path/to/images.js');

gulp.task('default', function () {
  gulp.src('source/images/**/*')
    .pipe(responsive(images))
    .pipe(gulp.dest('dist/images'));
});
```

**Comment by dcgauld** [comment]
Awesome! I'll get this in ASAP. Thanks for your help.

**Comment by OleVik** [comment]
@dcgauld You really should update the readme with the options code-mattclaffey specified above, they are paramount for using the package. Also, a way of specifying them for the entire pipeline would be ideal: For example setting the quality of all images to 85 unless overridden by specific configurations.

The package deserves attention, as it is one of preciously few alternatives to gulp-responsive with sharp, of which the latter is very painful to install and maintain on Windows. GraphicsMagick, on the other hand, is great!

**Comment by dcgauld** [comment]
Agreed, will get around to updating the README soon. If you have improvement suggestions, why not open a pull request? :)

**Comment by OleVik** [comment]
I did a quick pull request with an updated README.
